---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/julien-jungo/martian-bank-demo-ui
          env:
            {{- if .Values.nginx.enabled }}
            - name: VITE_USERS_URL
              value: /api/users
            - name: VITE_ATM_URL
              value: /api/atm
            - name: VITE_ACCOUNTS_URL
              value: /api/account
            - name: VITE_TRANSFER_URL
              value: /api/transaction
            - name: VITE_LOAN_URL
              value: /api/loan
            {{- else }}
            - name: VITE_USERS_URL
              value: http://{{ .Values.nginx.dashboardIP }}:5000/api/users
            - name: VITE_ATM_URL
              value: http://{{ .Values.nginx.dashboardIP }}:5000/api/atm/
            - name: VITE_ACCOUNTS_URL
              value: http://{{ .Values.nginx.dashboardIP }}:5000/account/
            - name: VITE_TRANSFER_URL
              value: http://{{ .Values.nginx.dashboardIP }}:5000/transaction/
            - name: VITE_LOAN_URL
              value: http://{{ .Values.nginx.dashboardIP }}:5000/loan/
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  {{- if not .Values.nginx.enabled }}
  type: LoadBalancer
  {{- end }}
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
