name: "CI"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto
          git-user: 'GitHub Actions'
          git-user-email: 'actions@github.com'

  build:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service:
          - name: ui
            context: ./ui
          - name: nginx
            context: ./nginx
          - name: customer-auth
            context: ./customer-auth
          - name: atm-locator
            context: ./atm-locator
          - name: dashboard
            context: .
          - name: accounts
            context: .
          - name: loan
            context: .
          - name: transactions
            context: .
          - name: performance_locust
            context: ./performance_locust

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Version
        id: check
        run: |
          if git tag --points-at HEAD | grep -q "^${{ matrix.service.name }}-"; then
            TAG=$(git tag --points-at HEAD | grep "^${{ matrix.service.name }}-")
            echo "version=${TAG#*-}" >> $GITHUB_OUTPUT
          fi

      - if: ${{ steps.check.outputs.version }}
        name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.check.outputs.version }}
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - if: ${{ steps.check.outputs.version }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 2

      - if: ${{ steps.check.outputs.version }}
        name: Build and Push Images
        uses: docker/build-push-action@v3.3.0
        with:
          context: ${{ matrix.service.context }}
          file: ./${{ matrix.service.name }}/Dockerfile
          tags: ghcr.io/${{ github.repository }}-${{ matrix.service.name }}:${{ steps.check.outputs.version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha
          push: true
